<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.2.0" />
	</ItemGroup>
	
    <ItemGroup>
      <Compile Remove="Command\**" />
      <EmbeddedResource Remove="Command\**" />
      <None Remove="Command\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\ServiceHosts\ShareMicroservice\ShareMicroservice.csproj" />
      <ProjectReference Include="..\ShareMicroservice.Domain\ShareMicroservice.Domain.csproj" />
    </ItemGroup>

</Project>
